###


POST http://localhost:8080/cars
content-type: application/json

{
    "Make":  "Scion",
    "Model": "TC",
    "Year": 2009,
    "Miles": 150000,
    "Drive": "FWD",
    "Engine": "1.5",
    "horsePower": "150"
}

###
GET http://localhost:8080/cars/65d8de9400ee6048a5290533
###
PUT http://localhost:8080/cars/65ced97c1b43d6fc1d921791
content-type: application/json

{
    "Make":  "Audi",
    "Model": "A-4",
    "Year": "2017",
    "Miles": "90,000",
    "Drive": "AWD",
    "Engine": "2.0 V6",
    "horsePower": "261"
}

###

DELETE http://localhost:8080/cars/65ced97c1b43d6fc1d921791 HTTP/1.1