###


POST http://localhost:8080/cars
content-type: application/json

{
    "Make":  "Audi",
    "Model": "A-4",
    "Year": "2017",
    "Miles": "90,000",
    "Drive": "AWD",
    "Engine": "2.0 V6",
    "horsePower": "261"
}

###
GET http://localhost:8080/cars/65ced907ba2b6cbde9e66452
###
PUT http://localhost:8080/cars/65ced97c1b43d6fc1d921791
content-type: application/json

{
    "Make":  "Audi",
    "Model": "A-4",
    "Year": "2017",
    "Miles": "90,000",
    "Drive": "AWD",
    "Engine": "2.0 V6",
    "horsePower": "261"
}

###

DELETE http://localhost:8080/cars/65ced97c1b43d6fc1d921791 HTTP/1.1